### ISSUE TITLE
Please specify license all code that copied from PyThaiNLP

### ISSUE THREAD

**Issue by wannaphong** [thirawat69/PyThaiAddr#1]
PyThaiNLP use [Apache-2.0 license](https://github.com/PyThaiNLP/pythainlp/blob/dev/LICENSE). If you copied the code that use Apache-2.0 license, you needs to specify Apache-2.0 license in the code (only the code that use Apache-2.0 license).

**Comment by thirawat69** [comment]
I apologize for the mistakes, I want to fix it properly Can you explain more?
--
สวัสดีครับ ต้องขออภัยในความผิดพลาดตรงส่วนของ license ด้วยนะครับ
พอจะช่วยอธิบายวิธีแก้ไขเพิ่มเติมให้หน่อยได้ไหมครับ
.
ผมต้องนำข้อความแสดงถึง license ไปไว้ตรงส่วนบนสุดของแต่ละไฟล์ ที่มีการนำมาใช้ (ดัดแปลง/แก้ไข) ใช่ไหมครับ
หรือว่าต้องเปลี่ยน license ของทั้งโปรเจคเลย 
.
ขอบคุณครับ

**Comment by wannaphong** [comment]
> ## I apologize for the mistakes, I want to fix it properly Can you explain more?
> 
> สวัสดีครับ ต้องขออภัยในความผิดพลาดตรงส่วนของ license ด้วยนะครับ พอจะช่วยอธิบายวิธีแก้ไขเพิ่มเติมให้หน่อยได้ไหมครับ . ผมต้องนำข้อความแสดงถึง license ไปไว้ตรงส่วนบนสุดของแต่ละไฟล์ ที่มีการนำมาใช้ (ดัดแปลง/แก้ไข) ใช่ไหมครับ หรือว่าต้องเปลี่ยน license ของทั้งโปรเจคเลย . ขอบคุณครับ

เฉพาะโค้ดส่วน (ดัดแปลง/แก้ไข) ที่เอามาจาก pythainlp ครับ เพราะ pythainlp ใช้ Apache-2.0 license ไม่ได้ใช้ MIT license ครับ โปรเจคคุณประกาศเป็น MIT license โดยที่ไม่ได้ระบุองค์ประกอบโค้ดส่วนที่เป็นคนละ license อาจจะมีปัญหาตามมาได้ครับ ตัวอย่างเช่น คนที่เห็นโปรเจคคุณเอาไปใช้ต่อ อาจคิดว่า ใช้ MIT license เอาโค้ด newmm trie ไปใช้โปรเจคอื่น เอาไปใช้ในโปรแกรมค้าขาย หรือโมต่อแล้วตั้งขาย ไม่ให้เครติด pythainlp ที่เป็นต้นฉบับ อาจจะมีปัญหาทางด้านกฎหมายตามมาได้ รวมถึงคนที่เป็นต้นฉบับจะไม่ได้เครติดอย่างที่ควรจะได้ครับ

**Comment by thirawat69** [comment]
> เฉพาะโค้ดส่วน (ดัดแปลง/แก้ไข) ที่เอามาจาก pythainlp ครับ เพราะ pythainlp ใช้ Apache-2.0 license ไม่ได้ใช้ MIT license ครับ โปรเจคคุณประกาศเป็น MIT license โดยที่ไม่ได้ระบุองค์ประกอบโค้ดส่วนที่เป็นคนละ license อาจจะมีปัญหาตามมาได้ครับ ตัวอย่างเช่น คนที่เห็นโปรเจคคุณเอาไปใช้ต่อ อาจคิดว่า ใช้ MIT license เอาโค้ด newmm trie ไปใช้โปรเจคอื่น เอาไปใช้ในโปรแกรมค้าขาย หรือโมต่อแล้วตั้งขาย ไม่ให้เครติด pythainlp ที่เป็นต้นฉบับ อาจจะมีปัญหาทางด้านกฎหมายตามมาได้ รวมถึงคนที่เป็นต้นฉบับจะไม่ได้เครติดอย่างที่ควรจะได้ครับ

สอบถามเพิ่มเติมเพื่อความชัดเจนนะครับ
1. เพิ่มข้อความที่ บ่งบอกถึงที่มาของโค้ด ในไฟล์นั้นๆ
2. เพิ่มเนื้อหาใน license  ที่บอกว่าส่วนไหนเป็นคนละ license  บ้าง

อย่างนี้ใช่ไหมครับ หรือทำแค่ข้อ 1 อย่างเดียว
หรือผมควรเปลี่ยน license ของโปรเจคเป็น Apache-2.0 license ไปเลยครับ

**Comment by wannaphong** [comment]
จริง ๆ ทำได้ทั้งสองข้อครับ ตัวอย่างเช่น android https://source.android.com/license?hl=th กับระบุที่ส่วนหัวโค้ดครับ

**Comment by thirawat69** [comment]
ขอบคุณมากครับ จะรีบดำเนินการแก้ไขให้นะครับ ขอบคุณที่มาเตือนมากๆเลยครับ

**Comment by thirawat69** [comment]
Fixed: Add the following text 
"""
this code is under Apache-2.0 license from PyThaiNLP library.
https://github.com/PyThaiNLP
"""
to the file
- tokenize/newmm.py
- tokenize/tcc.py
- tokenize/tokenizer.py

If nothing more we would like to close this issue.
